"""Utilities to build gnoi."""

load(
    "@sonic_protobuf//:defs.bzl",
    "WELL_KNOWN_PROTO_PATH",
    "protoc_genrule",
)

# The gnoi protos rebootbackend needs, as paths under @gnoi_protos,
# which mirrors the vendored //gnoi submodule.
_GNOI_PROTOS = [
    "types/types.proto",
    "common/common.proto",
    "system/system.proto",
]

# The generated sources import each other as "github.com/openconfig/gnoi/types/types.pb.h".
_GNOI_IMPORT_PREFIX = "github.com/openconfig/gnoi"

_GEN_ROOT = "gen"

def _generated(proto, extension):
    return "{root}/{prefix}/{stem}.{extension}".format(
        extension = extension,
        prefix = _GNOI_IMPORT_PREFIX,
        root = _GEN_ROOT,
        stem = proto[:-len(".proto")] + ".pb",
    )

def gnoi_cc_protos(name):
    """A cc_library of the gnoi protos, generated by the base layer's protoc.

    TODO(bazel-ready): This could be turned into a series of cc_proto_library calls
    when we can stop vendoring in libprotobuf from debian in src/protobuf.

    Args:
        name: the cc_library to define.
    """
    sources = [_generated(proto, "cc") for proto in _GNOI_PROTOS]
    headers = [_generated(proto, "h") for proto in _GNOI_PROTOS]

    # @gnoi_protos' root.
    # We need to derive it from a file, because a repository's own path is not accessible in a genrule.
    # derived from a file in it because a repository's own
    # path is not otherwise addressable from a genrule.
    gnoi_root = "$$(dirname $$(dirname $(execpath @gnoi_protos//:{proto})))".format(
        proto = _GNOI_PROTOS[0],
    )
    protoc_args = " ".join([
        "--cpp_out=$(RULEDIR)/{root}".format(root = _GEN_ROOT),
        "--proto_path={prefix}=$$GNOI_ROOT".format(prefix = _GNOI_IMPORT_PREFIX),
        "--proto_path=" + WELL_KNOWN_PROTO_PATH,
    ] + ["$$GNOI_ROOT/" + proto for proto in _GNOI_PROTOS])

    protoc_genrule(
        name = name + "_gen",
        srcs = ["@gnoi_protos//:" + proto for proto in _GNOI_PROTOS],
        outs = sources + headers,
        setup = "GNOI_ROOT={gnoi_root}; ".format(gnoi_root = gnoi_root),
        args = protoc_args,
    )

    native.cc_library(
        name = name,
        srcs = sources,
        hdrs = headers,
        includes = [
            _GEN_ROOT,
            _GEN_ROOT + "/" + _GNOI_IMPORT_PREFIX,
        ],
        deps = ["@sonic_protobuf//:libprotobuf"],
    )
